name: Conquest
main: com.blockempires.conquest.ConquestPlugin
version: 0.1
depend: [WorldGuard, Vault]
commands:
    conquest:
        description: Conquest commands
        usage: /conquest

permissions:
    conquest.edit:
        description: Allows you to edit conquest setups
        default: false
    